-- CRIANDO BANCO DE DADOS 
CREATE DATABASE ESTUDOS

-- CRIANDO A PRIMEIRA TABELA
CREATE TABLE CADASTRO  (
	CODIGO INT NOT NULL PRIMARY KEY IDENTITY,
	NOME VARCHAR (400) NOT NULL,
	DBNAME VARCHAR (20) NOT NULL UNIQUE,
	SENHA VARCHAR (15) NOT NULL,
	EMAIL VARCHAR (50) NOT NULL UNIQUE,
	TELEFONE VARCHAR (15),
	SITUACAO BIT NOT NULL,
	OBSERVACAO VARCHAR (250) NOT NULL,
)
