algoritmo "MeuPrimeiroAlgoritmo"
// AUTOR: TALES OLIVER
// DATA: 27/07/2021
var
// SEÇÃO DE DECLARAÇÃO DE VARIÁVEIS
nome: caracter
idade: inteiro
altura: real
casado: logico
inicio
// SEÇÃO DE COMANDOS
      escreval("Digite o seu nome:")
      leia(nome)
      escreval("Digite a sua idade:")
      leia(idade)
      escreval("Digite a sua altura:")
      leia(altura)
      escreval("Seu nome é ",nome, ", sua idade é ",idade, " e a sua altura é ", altura, ".")
fimalgoritmo